# Generated by Django 3.1.2 on 2021-04-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancha', models.CharField(max_length=80)),
                ('codigoInterno', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('vestuarioDisponible', models.BooleanField()),
                ('iluminacion', models.BooleanField()),
                ('cespedSintetico', models.BooleanField()),
            ],
        ),
    ]
