# Generated by Django 3.1.2 on 2021-04-14 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.CharField(max_length=40)),
                ('cliente', models.CharField(max_length=50)),
                ('empleado', models.CharField(max_length=50)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.cancha')),
            ],
        ),
    ]
