# Generated by Django 3.1.2 on 2021-04-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='reserva',
        ),
    ]
