# Generated by Django 3.1.2 on 2021-04-14 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_remove_reserva_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 14, 15, 57, 59, 25455, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 4, 14, 15, 58, 23, 935955, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
