# Generated by Django 3.1.2 on 2021-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20210414_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
