# Generated by Django 3.1.2 on 2021-04-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20210414_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='timestamp',
        ),
    ]
